# Generated by Django 6.0.4 on 2026-05-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_addslot',
        ),
    ]
