# Generated by Django 6.0.4 on 2026-05-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_slot',
        ),
    ]
