# Generated by Django 6.0.4 on 2026-05-04 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_tbl_psychologist'),
        ('Psychologist', '0004_delete_tbl_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_fromtime', models.TimeField()),
                ('slot_totime', models.TimeField()),
                ('psychologist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_psychologist')),
            ],
        ),
    ]
