# Generated by Django 6.0.4 on 2026-04-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_tb1_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='tb1_Brand',
        ),
    ]
