# Generated by Django 6.0.4 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0005_tbl_brand_delete_tb1_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=60)),
            ],
        ),
    ]
