# Generated by Django 6.0.4 on 2026-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
