# Generated by Django 6.0.4 on 2026-04-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_rename_category_tbl_subcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_subcategory',
            old_name='sub_name',
            new_name='subcategory_name',
        ),
    ]
