# Generated by Django 6.0.4 on 2026-05-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_rename_sub_name_tbl_subcategory_subcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questionlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionlevel_level', models.CharField(max_length=60)),
            ],
        ),
    ]
