# Generated by Django 6.0.4 on 2026-05-13 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_tbl_questionlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=60)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_questionlevel')),
            ],
        ),
    ]
