# Generated by Django 6.0.4 on 2026-05-13 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0012_tbl_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_option', models.CharField(max_length=60)),
                ('option_status', models.IntegerField(default=0)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_question')),
            ],
        ),
    ]
