# Generated by Django 6.0.4 on 2026-05-17 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0013_tbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_price', models.IntegerField(default=0)),
                ('product_image', models.FileField(upload_to='Assets/UserDocs/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_subcategory')),
            ],
        ),
    ]
