# Generated by Django 6.0.4 on 2026-05-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0014_tbl_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_question',
            name='level_id',
        ),
        migrations.DeleteModel(
            name='tbl_options',
        ),
        migrations.DeleteModel(
            name='tbl_question',
        ),
        migrations.DeleteModel(
            name='tbl_questionlevel',
        ),
    ]
