# Generated by Django 6.0.4 on 2026-05-21 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0015_remove_tbl_question_level_id_delete_tbl_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=50)),
                ('question_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_questionlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionlevel_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_content', models.CharField(max_length=50)),
                ('stress_weight', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_question')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_question',
            name='questionlevel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_questionlevel'),
        ),
    ]
