# Generated by Django 6.0.4 on 2026-05-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0016_tbl_question_tbl_questionlevel_tbl_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_remedies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedies_title', models.CharField(max_length=50)),
                ('remedies_description', models.CharField(max_length=50)),
                ('remedies_stresslevel', models.CharField(max_length=50)),
            ],
        ),
    ]
