# Generated by Django 6.0.4 on 2026-04-22 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0010_rename_sub_name_tbl_subcategory_subcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newuser_name', models.CharField(max_length=60)),
                ('newuser_contact', models.CharField(max_length=60)),
                ('newuser_email', models.CharField(max_length=60)),
                ('newuser_password', models.CharField(max_length=60)),
                ('newuser_address', models.CharField(max_length=60)),
                ('newuser_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('newuser_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
