# Generated by Django 6.0.4 on 2026-04-22 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrator', '0010_rename_sub_name_tbl_subcategory_subcategory_name'),
        ('Guest', '0002_delete_tbl_newuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_newuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=60)),
                ('user_gender', models.CharField(max_length=60)),
                ('user_dob', models.DateField()),
                ('user_contact', models.CharField(max_length=60)),
                ('user_email', models.CharField(max_length=60)),
                ('user_password', models.CharField(max_length=60)),
                ('user_address', models.CharField(max_length=60)),
                ('user_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
