# Generated by Django 6.0.4 on 2026-04-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_psychologist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_psychologist',
            old_name='psychologist_addresss',
            new_name='psychologist_address',
        ),
        migrations.RemoveField(
            model_name='tbl_psychologist',
            name='psychologist_district',
        ),
    ]
