# Generated by Django 6.0.4 on 2026-05-01 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_rename_psychologist_addresss_tbl_psychologist_psychologist_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_psychologist',
        ),
    ]
