# Generated by Django 6.0.4 on 2026-05-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_rename_sub_name_tbl_subcategory_subcategory_name'),
        ('Guest', '0006_delete_tbl_psychologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_psychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychologist_name', models.CharField(max_length=60)),
                ('psychologist_email', models.CharField(max_length=60)),
                ('psychologist_contact', models.CharField(max_length=60)),
                ('psychologist_address', models.CharField(max_length=60)),
                ('psychologist_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('psychologist_proof', models.FileField(upload_to='Assets/UserDocs/')),
                ('psychologist_password', models.CharField(max_length=60)),
                ('psychologist_status', models.IntegerField(default=0)),
                ('psychologist_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.tbl_place')),
            ],
        ),
    ]
