# Generated by Django 6.0.4 on 2026-05-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_psychologist'),
        ('Psychologist', '0005_initial'),
        ('User', '0008_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default=0)),
                ('booking_description', models.CharField(max_length=60)),
                ('booking_date', models.DateField()),
                ('booking_amount', models.IntegerField(default=0)),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Psychologist.tbl_slot')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
